class_file_path: '/media/johannes-f/F038E25338E217FC/Users/Merkur-PC/Desktop/Plantnet300K/plantnet_300K/plantnet300K_species_names.json'
data_dir: '/media/johannes-f/F038E25338E217FC/Users/Merkur-PC/Desktop/Plantnet300K/plantnet_300K/'
